import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
const mime = {
  html: "text/html; charset=utf-8",
  css: "text/css; charset=utf-8",
  js: "application/javascript; charset=utf-8",
  svg: "image/svg+xml",
  png: "image/png",
  jpg: "image/jpeg",
  ttf: "font/ttf",
  woff2: "font/woff2",
  txt: "text/plain; charset=utf-8",
};
const assets = {};
// Ship the licensed variable font locally so private workspaces need no font CDN.
const fontPackage = "node_modules/@fontsource-variable/noto-sans-arabic";
fs.mkdirSync("public/fonts", { recursive: true });
for (const subset of ["arabic", "latin"]) {
  fs.copyFileSync(
    `${fontPackage}/files/noto-sans-arabic-${subset}-wght-normal.woff2`,
    `public/fonts/nailat-${subset}.woff2`,
  );
}
fs.copyFileSync(`${fontPackage}/LICENSE`, "public/fonts/OFL.txt");
function walk(dir) {
  for (const item of fs.readdirSync(dir, { withFileTypes: true })) {
    const file = path.join(dir, item.name);
    if (item.isDirectory()) {
      walk(file);
      continue;
    }
    const ext = path.extname(file).slice(1),
      binary = ["png", "jpg", "ttf", "woff2"].includes(ext),
      key = "/" + path.relative("public", file).split(path.sep).join("/");
    let body = fs.readFileSync(file, binary ? "base64" : "utf8");
    if (ext === "html") {
      body = body.replace(
        /((?:src|href)=")\/(.*?\.(?:js|css))"/g,
        (_, prefix, resource) => {
          const hash = createHash("sha256")
            .update(fs.readFileSync(path.join("public", resource)))
            .digest("hex")
            .slice(0, 12);
          return `${prefix}/${resource}?v=${hash}"`;
        },
      );
    }
    assets[key] = {
      type: mime[ext] || "application/octet-stream",
      encoding: binary ? "base64" : "utf8",
      body,
    };
  }
}
walk("public");
fs.writeFileSync(
  "generated.js",
  "// Generated by npm run build.\nexport const ASSETS=" +
    JSON.stringify(assets) +
    ";\n",
);
fs.rmSync("dist", { recursive: true, force: true });
fs.mkdirSync("dist/server", { recursive: true });
fs.copyFileSync("worker.js", "dist/server/index.js");
fs.copyFileSync("generated.js", "dist/server/generated.js");
fs.cpSync("lib", "dist/server/lib", { recursive: true });
fs.cpSync("public", "dist/client", { recursive: true });
fs.writeFileSync("dist/client/index.html", assets["/index.html"].body);
fs.mkdirSync("dist/.openai", { recursive: true });
fs.copyFileSync(".openai/hosting.json", "dist/.openai/hosting.json");
fs.cpSync("drizzle", "dist/.openai/drizzle", { recursive: true });
fs.writeFileSync(
  "dist/server/wrangler.json",
  JSON.stringify(
    {
      name: "diwan-almazayen",
      main: "index.js",
      compatibility_date: "2026-06-01",
      assets: { directory: "../client", binding: "ASSETS" },
      d1_databases: [
        {
          binding: "DB",
          database_name: "diwan",
          migrations_dir: "../.openai/drizzle",
        },
      ],
      r2_buckets: [{ binding: "BUCKET", bucket_name: "diwan-files" }],
    },
    null,
    2,
  ),
);
console.log(
  "Built Diwan worker with " +
    Object.keys(assets).length +
    " assets and versioned migrations.",
);
