CREATE TABLE "nl_advance_entries" (
	"id" text PRIMARY KEY NOT NULL,
	"advance_id" text NOT NULL,
	"meta" text DEFAULT '{}' NOT NULL,
	"type" text NOT NULL,
	"amount" bigint NOT NULL,
	"date" text NOT NULL,
	"payment_id" text,
	"reference" text DEFAULT '' NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL,
	CONSTRAINT "nl_advance_entry_positive" CHECK ("nl_advance_entries"."amount">0)
);
--> statement-breakpoint
ALTER TABLE "nl_advance_entries" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_advances" (
	"id" text PRIMARY KEY NOT NULL,
	"project_id" text NOT NULL,
	"assignee_id" text NOT NULL,
	"meta" text DEFAULT '{}' NOT NULL,
	"title" text NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_advances" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_agent_turns" (
	"id" text PRIMARY KEY NOT NULL,
	"member_id" text NOT NULL,
	"context" text DEFAULT '{}' NOT NULL,
	"message" text NOT NULL,
	"reply" text NOT NULL,
	"proposal" text DEFAULT '{}' NOT NULL,
	"tokens" integer DEFAULT 0 NOT NULL,
	"created" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_agent_turns" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_asset_numbers" (
	"number" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nl_asset_numbers_number_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"asset_id" text NOT NULL,
	CONSTRAINT "nl_asset_numbers_asset_id_unique" UNIQUE("asset_id")
);
--> statement-breakpoint
ALTER TABLE "nl_asset_numbers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_assets" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"kind" text DEFAULT 'quantity' NOT NULL,
	"ownership" text DEFAULT 'owned' NOT NULL,
	"category" text DEFAULT '' NOT NULL,
	"quantity" integer NOT NULL,
	"location" text DEFAULT '' NOT NULL,
	"serial" text,
	"condition" text DEFAULT 'ready' NOT NULL,
	"meta" text DEFAULT '{}' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL,
	CONSTRAINT "nl_asset_quantity_nonnegative" CHECK ("nl_assets"."quantity">=0)
);
--> statement-breakpoint
ALTER TABLE "nl_assets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_audit" (
	"id" text PRIMARY KEY NOT NULL,
	"actor" text NOT NULL,
	"action" text NOT NULL,
	"resource" text NOT NULL,
	"entity_id" text NOT NULL,
	"project_id" text,
	"detail" text DEFAULT '' NOT NULL,
	"created" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_audit" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_bundles" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"grants" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_bundles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_comments" (
	"id" text PRIMARY KEY NOT NULL,
	"task_id" text NOT NULL,
	"meta" text DEFAULT '{}' NOT NULL,
	"body" text NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_comments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_committees" (
	"id" text PRIMARY KEY NOT NULL,
	"project_id" text NOT NULL,
	"config" text DEFAULT '{}' NOT NULL,
	"name" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"manager_id" text,
	"members" text DEFAULT '[]' NOT NULL,
	"statuses" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_committees" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_contact_preferences" (
	"member_id" text PRIMARY KEY NOT NULL,
	"whatsapp" integer DEFAULT 0 NOT NULL,
	"consent_at" text
);
--> statement-breakpoint
ALTER TABLE "nl_contact_preferences" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_delivery_jobs" (
	"id" text PRIMARY KEY NOT NULL,
	"provider_id" text,
	"status" text NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"next_at" bigint DEFAULT 0 NOT NULL,
	"error" text DEFAULT '' NOT NULL,
	"updated" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_delivery_jobs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_expenses" (
	"id" text PRIMARY KEY NOT NULL,
	"project_id" text NOT NULL,
	"supplier_id" text,
	"title" text NOT NULL,
	"number" text,
	"category" text NOT NULL,
	"amount" bigint NOT NULL,
	"tax" bigint DEFAULT 0 NOT NULL,
	"date" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"meta" text DEFAULT '{}' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL,
	CONSTRAINT "nl_expense_amount_positive" CHECK ("nl_expenses"."amount">0),
	CONSTRAINT "nl_expense_tax_valid" CHECK ("nl_expenses"."tax">=0 AND "nl_expenses"."tax"<="nl_expenses"."amount")
);
--> statement-breakpoint
ALTER TABLE "nl_expenses" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_files" (
	"id" text PRIMARY KEY NOT NULL,
	"entity_type" text NOT NULL,
	"entity_id" text NOT NULL,
	"meta" text DEFAULT '{}' NOT NULL,
	"name" text NOT NULL,
	"mime" text NOT NULL,
	"size" integer NOT NULL,
	"object_key" text NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_files" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_guards" (
	"id" text PRIMARY KEY NOT NULL,
	"value" integer NOT NULL,
	CONSTRAINT "nl_guard_changed" CHECK ("nl_guards"."value"=1)
);
--> statement-breakpoint
ALTER TABLE "nl_guards" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_guides" (
	"id" text PRIMARY KEY NOT NULL,
	"project_id" text NOT NULL,
	"task_id" text,
	"title" text NOT NULL,
	"content" text NOT NULL,
	"template_version" integer NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_guides" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_integration_limits" (
	"key" text PRIMARY KEY NOT NULL,
	"hits" integer DEFAULT 0 NOT NULL,
	"expires" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_integration_limits" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_members" (
	"id" text PRIMARY KEY NOT NULL,
	"site_id" text,
	"name" text NOT NULL,
	"email" text,
	"phone" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"grants" text DEFAULT '[]' NOT NULL,
	"bundles" text DEFAULT '[]' NOT NULL,
	"team" text DEFAULT '' NOT NULL,
	"verified" integer DEFAULT 0 NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_movements" (
	"id" text PRIMARY KEY NOT NULL,
	"asset_id" text NOT NULL,
	"project_id" text,
	"member_id" text,
	"meta" text DEFAULT '{}' NOT NULL,
	"type" text NOT NULL,
	"quantity" integer NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL,
	CONSTRAINT "nl_movement_positive" CHECK ("nl_movements"."quantity">0)
);
--> statement-breakpoint
ALTER TABLE "nl_movements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_notifications" (
	"id" text PRIMARY KEY NOT NULL,
	"member_id" text NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"resource" text NOT NULL,
	"entity_id" text NOT NULL,
	"project_id" text,
	"channel" text DEFAULT 'in_app' NOT NULL,
	"status" text DEFAULT 'unread' NOT NULL,
	"created" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_notifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_otp" (
	"id" text PRIMARY KEY NOT NULL,
	"site_id" text NOT NULL,
	"phone" text NOT NULL,
	"hash" text NOT NULL,
	"expires" bigint NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"used" integer DEFAULT 0 NOT NULL,
	"status" text DEFAULT 'sending' NOT NULL,
	"created" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_otp" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_payments" (
	"id" text PRIMARY KEY NOT NULL,
	"expense_id" text NOT NULL,
	"amount" bigint NOT NULL,
	"date" text NOT NULL,
	"reference" text DEFAULT '' NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL,
	CONSTRAINT "nl_payment_positive" CHECK ("nl_payments"."amount">0)
);
--> statement-breakpoint
ALTER TABLE "nl_payments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_projects" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"season" text DEFAULT '' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"start" text,
	"due" text,
	"budget" bigint DEFAULT 0 NOT NULL,
	"meta" text DEFAULT '{}' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL,
	CONSTRAINT "nl_project_budget_nonnegative" CHECK ("nl_projects"."budget">=0)
);
--> statement-breakpoint
ALTER TABLE "nl_projects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_receipts" (
	"id" text PRIMARY KEY NOT NULL,
	"actor" text NOT NULL,
	"hash" text NOT NULL,
	"result" text NOT NULL,
	"created" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_receipts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_suppliers" (
	"id" text PRIMARY KEY NOT NULL,
	"meta" text DEFAULT '{}' NOT NULL,
	"name" text NOT NULL,
	"phone" text,
	"email" text,
	"tax_number" text,
	"category" text DEFAULT '' NOT NULL,
	"notes" text DEFAULT '' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_suppliers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "nl_tasks" (
	"id" text PRIMARY KEY NOT NULL,
	"project_id" text NOT NULL,
	"title" text NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"assignee_id" text,
	"start" text,
	"due" text,
	"priority" text DEFAULT 'normal' NOT NULL,
	"status" text DEFAULT 'todo' NOT NULL,
	"parent_id" text,
	"meta" text DEFAULT '{}' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by" text NOT NULL,
	"created" text NOT NULL,
	"updated" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "nl_tasks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "nl_advance_entries" ADD CONSTRAINT "nl_advance_entries_advance_id_nl_advances_id_fk" FOREIGN KEY ("advance_id") REFERENCES "public"."nl_advances"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_advance_entries" ADD CONSTRAINT "nl_advance_entries_payment_id_nl_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."nl_payments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_advances" ADD CONSTRAINT "nl_advances_project_id_nl_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."nl_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_advances" ADD CONSTRAINT "nl_advances_assignee_id_nl_members_id_fk" FOREIGN KEY ("assignee_id") REFERENCES "public"."nl_members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_comments" ADD CONSTRAINT "nl_comments_task_id_nl_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."nl_tasks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_committees" ADD CONSTRAINT "nl_committees_project_id_nl_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."nl_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_committees" ADD CONSTRAINT "nl_committees_manager_id_nl_members_id_fk" FOREIGN KEY ("manager_id") REFERENCES "public"."nl_members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_expenses" ADD CONSTRAINT "nl_expenses_project_id_nl_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."nl_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_expenses" ADD CONSTRAINT "nl_expenses_supplier_id_nl_suppliers_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."nl_suppliers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_guides" ADD CONSTRAINT "nl_guides_project_id_nl_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."nl_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_guides" ADD CONSTRAINT "nl_guides_task_id_nl_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "public"."nl_tasks"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_movements" ADD CONSTRAINT "nl_movements_asset_id_nl_assets_id_fk" FOREIGN KEY ("asset_id") REFERENCES "public"."nl_assets"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_movements" ADD CONSTRAINT "nl_movements_project_id_nl_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."nl_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_movements" ADD CONSTRAINT "nl_movements_member_id_nl_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."nl_members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_payments" ADD CONSTRAINT "nl_payments_expense_id_nl_expenses_id_fk" FOREIGN KEY ("expense_id") REFERENCES "public"."nl_expenses"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_tasks" ADD CONSTRAINT "nl_tasks_project_id_nl_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."nl_projects"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "nl_tasks" ADD CONSTRAINT "nl_tasks_assignee_id_nl_members_id_fk" FOREIGN KEY ("assignee_id") REFERENCES "public"."nl_members"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "nl_advance_entries_advance" ON "nl_advance_entries" USING btree ("advance_id");--> statement-breakpoint
CREATE UNIQUE INDEX "nl_advance_payment" ON "nl_advance_entries" USING btree ("payment_id");--> statement-breakpoint
CREATE INDEX "nl_advances_project" ON "nl_advances" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "nl_agent_member" ON "nl_agent_turns" USING btree ("member_id","created");--> statement-breakpoint
CREATE UNIQUE INDEX "nl_asset_serial" ON "nl_assets" USING btree ("serial");--> statement-breakpoint
CREATE INDEX "nl_audit_created" ON "nl_audit" USING btree ("created");--> statement-breakpoint
CREATE INDEX "nl_comments_task" ON "nl_comments" USING btree ("task_id");--> statement-breakpoint
CREATE INDEX "nl_committees_project" ON "nl_committees" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "nl_delivery_provider" ON "nl_delivery_jobs" USING btree ("provider_id");--> statement-breakpoint
CREATE INDEX "nl_expenses_project" ON "nl_expenses" USING btree ("project_id");--> statement-breakpoint
CREATE UNIQUE INDEX "nl_expense_invoice_unique" ON "nl_expenses" USING btree ("project_id","supplier_id","number");--> statement-breakpoint
CREATE INDEX "nl_files_entity" ON "nl_files" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "nl_member_site" ON "nl_members" USING btree ("site_id");--> statement-breakpoint
CREATE UNIQUE INDEX "nl_member_phone" ON "nl_members" USING btree ("phone");--> statement-breakpoint
CREATE UNIQUE INDEX "nl_member_email" ON "nl_members" USING btree ("email");--> statement-breakpoint
CREATE INDEX "nl_movement_asset" ON "nl_movements" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "nl_notifications_member" ON "nl_notifications" USING btree ("member_id","created");--> statement-breakpoint
CREATE INDEX "nl_otp_identity" ON "nl_otp" USING btree ("site_id","created");--> statement-breakpoint
CREATE INDEX "nl_payments_expense" ON "nl_payments" USING btree ("expense_id");--> statement-breakpoint
CREATE INDEX "nl_tasks_project_due" ON "nl_tasks" USING btree ("project_id","due");--> statement-breakpoint
CREATE INDEX "nl_tasks_assignee" ON "nl_tasks" USING btree ("assignee_id");